### ISSUE TITLE
Please provide example screenshots for testsuite in Readme

### ISSUE THREAD

**Issue by susgo** [Fonata/DelphiScreenshotTestsuite#1]
Is it possible to get some example screenshots for the testsuite? I would like to talk about my experience with testing during a talk in usergroup about testing with codeception. Therefore I need some screens.

Also maybe this should be posted under company namespace, shouldn't it?

**Comment by Gogowitsch** [comment]
I have a German version of [these slides](https://quodata.de/fileadmin/temp/bu/PHPUnit_and_GitLab_CI.pdf) - would that help you? Let me know if you need .pptx instead of .pdf.

For some reason, I cannot create the GitHub organisation QuoData. Do you know who owns it?

**Comment by susgo** [comment]
Jep, these slides would help. Pptx would be more comfortable, but pdf is also okay. May be a module / package for faking test data is also interesting for you. 

GitHub User with this name already exists. May be Carsten has created it? I don't know. But if you have the login you can transform it into organization.

**Comment by susgo** [comment]
A thought: codeception is a very good solution for acceptance testing. Its PHP code only. Also by writing some page objects and helpers it is very clean.

**Comment by Gogowitsch** [comment]
I have played with and liked Codeception 👍. I also tried and liked the Mink framework which Drupal 8 core uses for browser tests. Getting a certain colleague on board on writing tests increases the overall success of our projects, so it is Drupal's `extends KernelTestBase` and CasperJS for now. That'll change, I'm sure.

**Comment by susgo** [comment]
I do all on my own at the moment. Good luck for finding a colleague for that.

**Comment by Gogowitsch** [comment]
Oh, sorry for my unclear words, I just didn't want to publicly shame someone. It wasn't about you. Sorry again. 

I really hope you'll have another experienced developer in your team soon! Until then I'd be more than happy to give you feedback for your code and take over tasks that feel too repetitive for you - I'm sure I could learn a lot that way.

**Comment by susgo** [comment]
Oh, it's  not only because of the code feedback, it's also about structure, some theoretical background, philosophy and innovation I would like to talk about and miss a second enthusiastic developer here. I think you can't help me in that things. May be its for that issues exactly the other way round and you could learn from me. But may be you are right and that's not correct.

**Comment by susgo** [comment]
Sorry, that's not meant in a negative way at all - hopefully you know that.

**Comment by Gogowitsch** [comment]
I know that. It’s a pleasure working with you.

**Comment by susgo** [comment]
May be. But it feels to me, that this is not at eye level and therefore nothing I search for.
